### ISSUE TITLE
Crate conflicts between `eframe` and `vsvg-viewer`.

### ISSUE THREAD

**Issue by invisageable** [abey79/vsvg#146]
I trying to used your nice looking crate in a my project using `eframe` and `vsvg-viewer`. My goal is to integrate the `svg-viewer` in my application. But I am not able to use it due to one conflict.

In my `Cargo.toml`:
```
[dependencies]
eframe = { version = "0.28.1", features = ["wgpu", "puffin"] }
vsvg-viewer = "0.4.0"
```

Then when I try to run `cargo run`:
```
error: failed to select a version for `web-sys`.
    ... required by package `wgpu v0.18.0`
    ... which satisfies dependency `wgpu = "^0.18"` of package `vsvg-viewer v0.4.0`
    ... which satisfies dependency `vsvg-viewer = "^0.4.0"` of package `my-crate v0.0.0`
versions that meet the requirements `^0.3.64` are: 0.3.69, 0.3.68, 0.3.67, 0.3.66, 0.3.65, 0.3.64

the package `wgpu` depends on `web-sys`, with features: `GpuComputePassTimestampWrite` but `web-sys` does not have these features.

all possible versions conflict with previously selected packages.

  previously selected package `web-sys v0.3.69`
    ... which satisfies dependency `web-sys = "^0.3.64"` of package `wgpu v0.18.0`
    ... which satisfies dependency `wgpu = "^0.18"` of package `vsvg-viewer v0.4.0`
    ... which satisfies dependency `vsvg-viewer = "^0.4.0"` of package `my-crate v0.0.0`

failed to select a version for `web-sys` which could resolve this conflict
```

**Comment by BryanDiLaura** [comment]
Heads up @invisageable: the version that you get from crates.io is old and has this incompatibility, but the unreleased version 0.5.0 in the git repository seems to work fine. 

If you git clone and then point your Cargo.toml towards your local copy it should work!

@abey79 would it be possible to do a release of v0.5.0 to prevent this? Or alternatively cherry-pick the couple of commits that would fix the v0.4 line?

**Comment by invisageable** [comment]
Oh thank you @BryanDiLaura, I didn't think I'd get an answer. I'll try to get version 0.5 soon (I've just seen the corresponding commits). I hope that @abey79 will be able to release version 0.5 soon.

**Comment by abey79** [comment]
Yeah a release is long overdue! I dont think I have a reason not to release as is. I'll try to get to it asap.

**Comment by invisageable** [comment]
Sounds very good. I'll wait for that version. Thanks @abey79

**Comment by abey79** [comment]
I didn't mean to discourage you from using the master branch either. At this stage of the project, it safe to assume that the master branch is just as good (bad?) as any release.

**Comment by invisageable** [comment]
My bad, I keep forgetting that you can attach the github link directly instead of the version number. Problem solved by doing: 

```
vsvg-viewer = { git = "https://github.com/abey79/vsvg" }
```

Thanks both of you.

**Comment by invisageable** [comment]
I close the ticket.

**Comment by abey79** [comment]
FWIW, 0.5.0 is now released.

**Comment by BryanDiLaura** [comment]
Thanks so much for the quick turnaround! v0.5 is working great!
